import type { CSSProperties } from 'react';

export const authStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#0f0f11',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 16px',
  },
  wordmark: {
    fontSize: '28px',
    fontWeight: 700,
    marginBottom: '6px',
    textAlign: 'center',
  },
  wordmarkBase: { color: '#fafafa' },
  wordmarkAccent: { color: '#6366f1' },
  tagline: {
    fontSize: '14px',
    color: '#71717a',
    marginBottom: '28px',
    textAlign: 'center',
  },
  card: {
    background: '#1c1c1f',
    border: '1px solid #2a2a2f',
    borderRadius: '12px',
    padding: '36px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
    width: '100%',
    maxWidth: '420px',
  },
  fieldGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 500,
    color: '#a1a1aa',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    border: '1px solid #2a2a2f',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '14px',
    color: '#fafafa',
    outline: 'none',
    boxSizing: 'border-box',
    background: '#0f0f11',
  },
  errorBox: {
    background: 'rgba(239,68,68,0.1)',
    border: '1px solid rgba(239,68,68,0.3)',
    borderRadius: '8px',
    padding: '12px 16px',
    color: '#f87171',
    fontSize: '14px',
    marginBottom: '16px',
  },
  button: {
    width: '100%',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '15px',
    fontWeight: 600,
    marginTop: '8px',
    background: '#6366f1',
  },
  footer: {
    textAlign: 'center',
    marginTop: '20px',
    fontSize: '14px',
    color: '#71717a',
  },
  link: {
    color: '#6366f1',
    fontWeight: 500,
    textDecoration: 'none',
  },
};
