import type { CSSProperties } from 'react';

export const authStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 16px',
  },
  wordmark: {
    fontSize: '28px',
    fontWeight: 700,
    marginBottom: '6px',
    textAlign: 'center',
  },
  wordmarkBase: { color: '#1a1a2e' },
  wordmarkAccent: { color: '#1a1a2e' },
  tagline: {
    fontSize: '14px',
    color: '#64748b',
    marginBottom: '28px',
    textAlign: 'center',
  },
  card: {
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    padding: '36px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
    width: '100%',
    maxWidth: '420px',
  },
  fieldGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 500,
    color: '#a1a1aa',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '14px',
    color: '#1a1a2e',
    outline: 'none',
    boxSizing: 'border-box',
    background: '#ffffff',
  },
  errorBox: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '8px',
    padding: '12px 16px',
    color: '#dc2626',
    fontSize: '14px',
    marginBottom: '16px',
  },
  button: {
    width: '100%',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '15px',
    fontWeight: 600,
    marginTop: '8px',
    background: '#1a1a1a',
  },
  footer: {
    textAlign: 'center',
    marginTop: '20px',
    fontSize: '14px',
    color: '#64748b',
  },
  link: {
    color: '#374151',
    fontWeight: 500,
    textDecoration: 'none',
  },
};
